const scope = () => {
    const CODES = {
        // create the root object which is referenced by the Proxy
        // HTTP status codes as of the HTTP/1.1 standard (RFC 7231)
        ACCEPTED: 202,
        BAD_GATEWAY: 502,
        BAD_REQUEST: 400,
        CONFLICT: 409,
        CONTINUE: 100,
        CREATED: 201,
        EXPECTATION_FAILED: 417,
        FAILED_DEPENDENCY : 424,
        FORBIDDEN: 403,
        GATEWAY_TIMEOUT: 504,
        GONE: 410,
        HTTP_VERSION_NOT_SUPPORTED: 505,
        IM_A_TEAPOT: 418,
        INSUFFICIENT_SPACE_ON_RESOURCE: 419,
        INSUFFICIENT_STORAGE: 507,
        INTERNAL_SERVER_ERROR: 500,
        LENGTH_REQUIRED: 411,
        LOCKED: 423,
        METHOD_FAILURE: 420,
        METHOD_NOT_ALLOWED: 405,
        MOVED_PERMANENTLY: 301,
        MOVED_TEMPORARILY: 302,
        MULTI_STATUS: 207,
        MULTIPLE_CHOICES: 300,
        NETWORK_AUTHENTICATION_REQUIRED: 511,
        NO_CONTENT: 204,
        NON_AUTHORITATIVE_INFORMATION: 203,
        NOT_ACCEPTABLE: 406,
        NOT_FOUND: 404,
        NOT_IMPLEMENTED: 501,
        NOT_MODIFIED: 304,
        OK: 200,
        PARTIAL_CONTENT: 206,
        PAYMENT_REQUIRED: 402,
        PERMANENT_REDIRECT: 308,
        PRECONDITION_FAILED: 412,
        PRECONDITION_REQUIRED: 428,
        PROCESSING: 102,
        PROXY_AUTHENTICATION_REQUIRED: 407,
        REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
        REQUEST_TIMEOUT: 408,
        REQUEST_TOO_LONG: 413,
        REQUEST_URI_TOO_LONG: 414,
        REQUESTED_RANGE_NOT_SATISFIABLE: 416,
        RESET_CONTENT: 205,
        SEE_OTHER: 303,
        SERVICE_UNAVAILABLE: 503,
        SWITCHING_PROTOCOLS: 101,
        TEMPORARY_REDIRECT: 307,
        TOO_MANY_REQUESTS: 429,
        UNAUTHORIZED: 401,
        UNPROCESSABLE_ENTITY: 422,
        UNSUPPORTED_MEDIA_TYPE: 415,
        USE_PROXY: 305,
    };

    // the Proxy will throw an error if a unknown status is used
    // this saves an extra function call to see if object exists
    const httpCodes = new Proxy(CODES, {
        get: (target, property) => {
            if (property in target) {
                return target[property];
            } else {
                throw new Error("http-codes: HTTP Code doesn't exist");
            }
        },
        // add the properties that map to CODE object propeties
        // this way we get autocomplete tooling for status codes
        ACCEPTED: null,
        BAD_GATEWAY: null,
        BAD_REQUEST: null,
        CONFLICT: null,
        CONTINUE: null,
        CREATED: null,
        EXPECTATION_FAILED: null,
        FAILED_DEPENDENCY: null,
        FORBIDDEN: null,
        GATEWAY_TIMEOUT: null,
        GONE: null,
        HTTP_VERSION_NOT_SUPPORTED: null,
        IM_A_TEAPOT: null,
        INSUFFICIENT_SPACE_ON_RESOURCE: null,
        INSUFFICIENT_STORAGE: null,
        INTERNAL_SERVER_ERROR: null,
        LENGTH_REQUIRED: null,
        LOCKED: null,
        METHOD_FAILURE: null,
        METHOD_NOT_ALLOWED: null,
        MOVED_PERMANENTLY: null,
        MOVED_TEMPORARILY: null,
        MULTI_STATUS: null,
        MULTIPLE_CHOICES: null,
        NETWORK_AUTHENTICATION_REQUIRED: null,
        NO_CONTENT: null,
        NON_AUTHORITATIVE_INFORMATION: null,
        NOT_ACCEPTABLE: null,
        NOT_FOUND: null,
        NOT_IMPLEMENTED: null,
        NOT_MODIFIED: null,
        OK: null,
        PARTIAL_CONTENT: null,
        PAYMENT_REQUIRED: null,
        PERMANENT_REDIRECT: null,
        PRECONDITION_FAILED: null,
        PRECONDITION_REQUIRED: null,
        PROCESSING: null,
        PROXY_AUTHENTICATION_REQUIRED: null,
        REQUEST_HEADER_FIELDS_TOO_LARGE: null,
        REQUEST_TIMEOUT: null,
        REQUEST_TOO_LONG: null,
        REQUEST_URI_TOO_LONG: null,
        REQUESTED_RANGE_NOT_SATISFIABLE: null,
        RESET_CONTENT: null,
        SEE_OTHER: null,
        SERVICE_UNAVAILABLE: null,
        SWITCHING_PROTOCOLS: null,
        TEMPORARY_REDIRECT: null,
        TOO_MANY_REQUESTS: null,
        UNAUTHORIZED: null,
        UNPROCESSABLE_ENTITY: null,
        UNSUPPORTED_MEDIA_TYPE: null,
        USE_PROXY: null,
    });

    return httpCodes;
}

module.exports = scope();
